version: "3.9"

services:
  db_fc_new:
    image: postgres:latest
    container_name: db_fc_new
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rad_elements
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
#    env_file:
#      - .env
  rad_components_new:
    build:
#      dockerfile: djsite/Dockerfile
      context: ./dbsite
    depends_on:
      - db_fc_new
    ports:
      - "8000:8000"
#    image: downloader
#    container_name: downloader
    environment:
      DEBUG: False
      POSTGRES_HOST: "db_fc"
      POSTGRES_PORT: 5432
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "rad_elements"
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
#  redis:
#    image: redis:alpine
#    ports:
#      - "6379:6379"
#    env_file:
#      - .env
#    command:
#        - /usr/local/bin/gunicorn
#        - djsite.wsgi:application
#        - --bind
#        - 0.0.0.0:8000
#
#
#
#  nginx:
#    container_name: nginx
#    image: nginx
#    volumes:
#      - ./conf/nginx.conf:/etc/nginx/nginx.conf
#      - static_volume:/static
#    depends_on:
#      - rad_components
#      - frontend
#    ports:
#      - "8001:8001"
#  apache:
#    build:
#      dockerfile: Dockerfile.apache
#    ports:
#      - "8080:8080"
  frontend_new:
    build:
      context: ./RadComponentsFront/RadComponentsFornt
#      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
    ports:
      - "5173:5173"

volumes:
  postgres_data:
  static_volume:
  media_volume:

